export const initialStateAction = (payload) => ({type : "INITIAL_STATE", payload})
export const postsSortAction = (payload) => ({type : "POSTS_SORT" , payload})
export const changeVisibiltyAction = (payload) => ({type : "CHANGE_VISIBILITY", payload})
export const addPostAction = (payload) => ({type : "ADD_POST" , payload})
export const deleteItemAction = (payload) => ({type : "DELETE_ITEM", payload})
export const changePostAction = (payload) => ({type : "CHANGE_POST" , payload})